sections:
- Eugenii Kuzakov
- Position of Interest
- Professional Experience
- Professional Strengths
- Language Proficiency
- Core Professional Skills
- DevOps Experience
- Software stack
- Contacts
