sections:
- Evgenii Kuzakov
- Position of Interest
- Professional Experience
- Professional Strengths
- Language Proficiency
- Core Professional Skills
- DevOps Experience
- Software stack
- Public relations
- Github projects
- Potential Work Arrangements (@remote)
- Education
- Contacts
- Employment
- '*Research and Development Senior DevOps engineer at* Hidden (Dec 2022 - Aug 2023)'
- SaltStack and Vault Integration Enhancement
- Research company wide IAM, Single Sign-On (SSO) solution
- SaltStack "Users" Formula Implementation
- '*Head of DevOps at* Latoken - crypto-currency exchange (Sep 2022 - Oct 2022)'
- Senior Responsibilities
- DevOps Tasks
- Senior DevOps at "Satel Pro" (https://satel.org) - software development company
  for government projects. (Oct 2019 Aug 2022)
- Leadership Role
- Comprehensive Rollout Rework
- Infrastructure as Code
- GitOps
- Configuration Management
- Continuous pipeline/deploy optimization
- Outdated
- Cryptocurrency Experience
