sections:
- Evgenii Kuzakov
- Position of Interest
- Professional Experience
- Professional Strengths
- Language Proficiency
- Core Professional Skills
- DevOps Experience
- Software stack
- Public relations
- Github projects
- Potential Work Arrangements (@remote)
- Education
- Contacts
- Employment
- '*Research and Development Senior DevOps engineer at* Hidden (Dec 2022 - Aug 2023)'
- SaltStack and Vault Integration Enhancement
- Research company wide IAM, Single Sign-On (SSO) solution
- SaltStack "Users" Formula Implementation
- '*Head of DevOps at* Latoken - crypto-currency exchange (Sep 2022 - Oct 2022)'
- Senior Responsibilities
- DevOps Tasks
- Senior DevOps at "Satel Pro" (https://satel.org) - software development company
  for government projects. (Oct 2019 Aug 2022)
- Leadership Role
- Comprehensive Rollout Rework
- Infrastructure as Code
- GitOps
- Configuration Management
- Continuous pipeline/deploy optimization
- "*Systems architect at* \xABIBS Expertise\xBB - the biggest systems integrator in\
  \ Russia (https://www.ibs.ru/)) (Oct 2016 - Aug 2019)"
- Systems Architect
- Chief Project Engineer
- '*Systems architect at* Technoserv - one of biggest, well known in Russia systems
  integrator company (*Jun 2014 - Aug 2016*)'
- the biggest project
- Systems architect/presale-manager at Open Technologies Ltd. - one of the most well
  known in Russia systems integrator company (Aug 2012 - Mar 2014)
- Business Development Manager (BDM)
- Pre-sales Manager
- Chief Technical Project Manager
- Head of data processing centers direction at "AMT Group" - one of well known in
  Russia systems integrator company (Jul 2008 - Jul 2012)
- From a technical standpoint
- Product Manager
- Engineer
- Senior systems engineer at "Open Technologies Ltd" - one of biggest, well known
  in Russia systems integrator company (Feb 2001 - Jun 2008)
- Systems administrator at "Plusinfo" internet channel and hosting provider (Sep 2000
  Nov 2000)
- Systems/network administrator at "International Trading Bank" - commercial bank
  http://www.itbank.ru (Jan 2000-Aug 2000)
- Systems/network administrator  at "Laboratory 321 Ltd" is one of biggest solution
  provider in Omsk city (http://www.lab321.ru) (July 1994 - Dec 1999)
- Outdated
- Cryptocurrency Experience
- Publications
- Trainings and certifications
