name: Convert Markdown to PDF

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install apt-get dependencies
      run: |
        sudo apt-get install pandoc texlive-latex-base

    - name: Convert Markdown to PDF
      run: |
        for file in *.md; do
          pandoc -s $file -o ${file%.*}.pdf
        done

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        for file in *.pdf; do
          git add $file
          git commit -m "Add generated $file"
        done    
        git push
