name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install apt-get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint fonts-liberation fonts-dejavu-core

      - name: Make converter executable
        run: chmod +x ./convert2pdf.sh

      - name: Convert Markdown to PDF
        run: ./convert2pdf.sh

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          for file in *.pdf; do
            git add "${file}"
          done
          git commit -m "Auto convert Markdown to PDF" || echo "No changes to commit"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push || echo "No changes to push"
