name: Convert Markdown to PDF

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install apt-get dependencies
      run: |
        sudo apt-get install pandoc weasyprint

    - name: Convert Markdown to PDF
      run: |
        for file in *.md; do
          pandoc --pdf-engine=weasyprint -s $file -o ${file%.*}.pdf
        done

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        for file in *.pdf; do
          git add $file
          git commit -m "Add generated $file"
        done
        git remote set-url origin https://${{ secrets.GH_REPO_UPDATE_USER }}:${{ secrets.GH_REPO_UPDATE_TOKEN }}@github.com/korkin25/cv.git
        git push